# Generated by Django 5.2.4 on 2025-08-06 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nombre_aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='imagen'),
        ),
    ]
